name: untitled1
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  weather: ^3.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Define the assets folder for images
  assets:
    - lib/assets/3.webp
    - lib/assets/4.webp
    - lib/assets/5.webp
    - lib/assets/6.webp
    - lib/assets/7.webp
    - lib/assets/8.webp
    - lib/assets/9.webp
    - lib/assets/10.webp
